version: '3'

services:
  database:
    image: postgres:14.0
    env_file:
      - envs/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - envs/postgres.env
      - envs/.env
    depends_on:
      - database

volumes:
  pg_data: