# Generated by Django 4.0.3 on 2022-03-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('sdk_version', models.CharField(max_length=255)),
                ('session_id', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
                ('error', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.BigIntegerField()),
                ('media_files', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('sdk_version', models.CharField(max_length=255)),
                ('session_id', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
            ],
        ),
    ]
